### ISSUE TITLE
undefined symbol: __sync_val_compare_and_swap_4 

### ISSUE THREAD

**Issue by remicollet** [json-c/json-c#131]
About: 64e36901a0614bf64a19bc3396469c66dcd0b015

On some old versions (reproduced on RHEL-5 i386) and perhaps on some specific arch:

     undefined symbol: __sync_val_compare_and_swap_4

**Comment by ayllon** [comment]
Hi,

If I am not mistaken, EL5 compiles using -m=i386 for 32 bits builds.
Atomic compare and swap ([CMPXCHG](http://en.wikipedia.org/wiki/Intel_80486#Improvements)) was added in i486, so I guess gcc puts a function call since it can not use that instruction, and no implementation is provided.

The macro [__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html) could be used to test wether the backend supports the builtin or not.

Regards.

**Comment by cpillonel** [comment]
I have the same issue on RH EL4, 32 bits.
How do I fix that?

Thank you.

**Comment by YYGCui** [comment]
I have the same issue on SLES 11 SP3 32bit.
I found a way to fix that:
when you exec configure cmd, add the follow parameters
`./configure CFLAGS="-march=i686"`

you can find the detail at [stackoverflow](http://stackoverflow.com/questions/8004241/how-to-compile-glibc-32bit-on-an-x86-64-machine)

**Comment by hawicz** [comment]
This should be fixed by changeset 0539191.

**Comment by mrnuke-adaptrum** [comment]
This issue still exists on arc770 targets when the "-matomic" option is not supplied to gcc.

Why not use C11 atomic types, and let the compiler figure out what's best?
